name: Notify
on:
  push:
    branches:
      - master
      - oauth
jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:        
    - uses: avkviring/telegram-github-action@v0.0.7
      env:
        telegram_to: ${{ secrets.TELEGRAM_TO }}  
        telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
        event: ${{ toJson(github.event) }}
